baseURL = 'https://yu-iskw.github.io/hugo-i18n-example/'
languageCode = 'ja-JP'
title = 'My New Hugo Site'
theme = "hugo-theme-relearn"

defaultContentLanguage = 'ja'
defaultContentLanguageInSubdir = true

[taxonomies]
  tag = "tags"
  # category = "categories"

[languages]
  [languages.ja]
    contentDir = 'content/ja'
    disabled = false
    languageCode = 'ja-JP'
    languageDirection = 'ltr'
    languageName = '日本語 (Japanese)'
    title = 'Hugoサイト'
    weight = 1

  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'My Hugo Site'
    weight = 2

[params]
  additionalContentLanguage = ['ja', 'en']
  math = true
