baseURL = 'https://example.org/'
languageCode = 'ja-JP'
title = 'My New Hugo Site'
theme = "hugo-theme-relearn"

defaultContentLanguage = 'ja'
defaultContentLanguageInSubdir = true

[taxonomies]
  tag = "tags"
  category = "categories"

[languages]
  [languages.ja]
    contentDir = 'content/ja'
    disabled = false
    languageCode = 'ja-JP'
    languageDirection = 'ltr'
    languageName = '日本語 (Japanese)'
    title = 'Hugoサイト'
    weight = 1

  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'My Hugo Site'
    weight = 2

[params]
  # Book configuration
  disablePathToLower = true
  enableGitInfo = true

  # (Optional, default true) Show or hide table of contents globally
  # You can also specify this parameter per page in front matter
  BookShowToC = true

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  # BookMenuBundle = "/ja/menu"

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  # BookSection = "docs"
  BookSection = "*"

  # This value is duplicate of $link-color for making active link highlight in menu bundle mode
  # BookMenuBundleActiveLinkColor: \#004ed0

  # Include JS scripts in pages. Disabled by default.
  # - Keep side menu on same scroll position during navigation
  BookEnableJS = true

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = "https://github.com/alex-shpak/hugo-book"

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  BookEditPath = "edit/master/exampleSite/content"
